

--假資料
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--新增資料(後台管理員)
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'Ben', 'EA10350', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'Ben', 0, 'lizahung1008@gmail.com', NULL,'ROLE_ADMIN',TO_DATE('2019-08-08','YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'Bob', 'EA10311', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'Bob', 0, 'lizahung1008@gmail.com', NULL,'ROLE_STAFF',TO_DATE('2019-08-08','YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'David', 'EA10349', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'David', 0, 'lizahung1008@gmail.com', NULL,'ROLE_STAFF',TO_DATE('2019-08-08','YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'Camilla', 'EA10354', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'Camilla', 0, 'lizahung1008@gmail.com', NULL,'ROLE_STAFF',TO_DATE('2019-08-08','YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'Anna', 'EA10310', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'Anna', 0, 'lizahung1008@gmail.com', NULL,'ROLE_STAFF',TO_DATE('2019-08-08','YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'Liza', 'EA10326', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'Liza', 0, 'lizahung1008@gmail.com', NULL,'ROLE_ADMIN',TO_DATE('2019-08-08','YYYY-MM-DD'));
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, EMP_ACCOUNT, EMP_PSW, EMP_NICKNAME, EMP_ACC_STATUS, EMP_EMAIL, EMP_PHOTO, EMP_ROLE, EMP_ARR_DATE) VALUES (EMPLOYEE_SEQ.NEXTVAL, 'Audrey', 'EA10341', '$2a$10$WkyyZG43xrI/ry.VzZEbV.HRtIdcWEpnYHzN.N86KuudzEmULvKmW', 'Audrey', 0, 'lizahung1008@gmail.com', NULL,'ROLE_STAFF',TO_DATE('2019-08-08','YYYY-MM-DD'));

--新增資料(後台功能)
INSERT INTO BACKFUNCTION (FUN_NO, FUN_NAME, FUN_URL) VALUES (BACKFUNCTION_SEQ.NEXTVAL, '員工管理','/employee/management');
INSERT INTO BACKFUNCTION (FUN_NO, FUN_NAME, FUN_URL) VALUES (BACKFUNCTION_SEQ.NEXTVAL, '員工權限管理','/employee-auth/management');
INSERT INTO BACKFUNCTION (FUN_NO, FUN_NAME, FUN_URL) VALUES (BACKFUNCTION_SEQ.NEXTVAL, '領養管理','/adoption/management');
INSERT INTO BACKFUNCTION (FUN_NO, FUN_NAME, FUN_URL) VALUES (BACKFUNCTION_SEQ.NEXTVAL, '領養申請','/adoption/application');
INSERT INTO BACKFUNCTION (FUN_NO, FUN_NAME, FUN_URL) VALUES (BACKFUNCTION_SEQ.NEXTVAL, '寵物管理','/adopet/management');

--新增資料(管理員權限)
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('1', '1');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('1', '2');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('1', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('1', '4');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('1', '5');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('2', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('2', '4');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('3', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('3', '4');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('4', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('4', '4');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('5', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('5', '4');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('6', '1');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('6', '2');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('6', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('6', '4');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('6', '5');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('7', '3');
INSERT INTO EMP_AUTHORITY (EMP_NO, FUN_NO) VALUES ('7', '4');

--新增資料(領養寵物)
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,PET_CHAR,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','老三','米克斯','1',TO_DATE('2019-08-08','YYYY-MM-DD'),'6','3','有雙立耳、圓滾滾的眼睛','0');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','蜜奇','貴賓','0',TO_DATE('2013-09-16','YYYY-MM-DD'),'5.5','3','2');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','小黑','拉布拉多','0',TO_DATE('2010-09-16','YYYY-MM-DD'),'16','4','2');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,PET_CHAR,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','Green','狐狸犬','0',TO_DATE('2018-03-06','YYYY-MM-DD'),'10','3','柔亮蓬鬆的白毛、充滿微笑的Green，十分俊帥','0');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,PET_CHAR,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','Yummy','米格魯','1',TO_DATE('2019-09-17','YYYY-MM-DD'),'13','4','窈窕身材和修長的四肢','0');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','巧巧','米克斯','0',TO_DATE('2019-08-31','YYYY-MM-DD'),'12','4','2');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','Qbo','拉布拉多','0',TO_DATE('2019-07-31','YYYY-MM-DD'),'20','5','1');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','錢寶','比利時狼犬','0',TO_DATE('2017-07-31','YYYY-MM-DD'),'20','5','1');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','比特媽媽','比特犬','0',TO_DATE('2018-12-31','YYYY-MM-DD'),'10','4','2');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','1','傑克','混種貓','0',TO_DATE('2016-12-31','YYYY-MM-DD'),'7','0','0');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','1','黑魯魯','混種貓','0',TO_DATE('2015-12-31','YYYY-MM-DD'),'7.5','0','0');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,PET_CHAR,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','1','小朋友','混種貓','1',TO_DATE('2020-09-17','YYYY-MM-DD'),'7.5','0','毛色為虎斑的橘貓','0');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','0','饅頭','法鬥','0',TO_DATE('2019-07-03','YYYY-MM-DD'),'7','3','2');
INSERT INTO ADO_PET (ADO_PET_NO,ADO_STATUS,PET_TYPE,PET_NAME,PET_BREED,PET_SEX,PET_BIRTH,PET_WEIGHT,PET_CAT,PET_CHAR,LOCATION)
VALUES(ADOPET_SEQ.NEXTVAL,'0','1','娜娜','混種貓','1',TO_DATE('2020-10-30','YYYY-MM-DD'),'5','0','毛色為黑白乳牛的貓','2');



commit;